### ISSUE TITLE
Change Defaults ID for openstack driver

### ISSUE THREAD

**Issue by allamand** [codenrhoden/ansible-role-rexray#1]
I had issue with default variables for Openstack Driver

```
rexray_os_authurl: ''
rexray_os_userid: 0
rexray_os_username: ''
rexray_os_password: ''
rexray_os_tenantid: 0
rexray_os_tenantname: ''
rexray_os_domainid: 0
rexray_os_domainname: ''
rexray_os_regionname: ''
rexray_os_availabilityzonename: ''
```

If we don't want to specify for instance `rexray_os_userid` then by default it will create the config file with : 

```
openstack:
  userID: 0
```

This doesn't works with OpenStack it should be : 

```
openstack:
  userID: 
```

or simply entirely remove the line (or comment it)

**Comment by codenrhoden** [comment]
@sebmoule thanks for writing this up!

Is it only the `userid` that has this issue?  In Slack, I think you said that having `0` as the default value was also a problem for `tenantid`, but maybe you found that was not the case?

**Comment by allamand** [comment]
@codenrhoden I confirm that `domainid` or `tenantid` has also the problem, the driver failed to start if I comment them or leave the default value.
